objectTypeMappings:
  Adres:
    sourceRoot: bag:Nummeraanduiding
    propertyMappings:
      identificatie:
        sourcePath: identificatie
      huisnummer:
        sourcePath: huisnummer
      huisnummertoevoeging:
        sourcePath: huisnummertoevoeging
      huisletter:
        sourcePath: huisletter
      postcode:
        sourcePath: postcode
      straatnaam:
        sourcePath: ligtAan/naam
      plaatsnaam:
        sourcePaths:
          - ligtIn/naam
          - ligtAan/ligtIn/naam
        transform: coalesce
      isHoofdadres:
        sourcePath: isHoofdadresVan/identificatie
        transform: nonNull
