logging:
  level:
    root: INFO

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.graphql.GraphQlAutoConfiguration
  graphql:
    graphiql:
      enabled: true

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

orchestrate:
  gateway:
    targetModel: ${TARGET_MODEL:imxgeo}
    mapping: ${MODEL_MAPPING:/mapping/imxgeo.yaml}
    dataPath: ${DATA_PATH:./data}
