logging:
  level:
    root: INFO
    nl.geostandaarden.imx.orchestrate: DEBUG

orchestrate:
  mapping: ../data/geo/mapping.yaml
  sources:
    adr:
      type: file
      options:
        dataPath: ../data/adr
    city:
      type: file
      options:
        dataPath: ../data/city
    land:
      type: file
      options:
        dataPath: ../data/land
    body:
      type: rest
      options:
        url: "https://brk.basisregistraties.overheid.nl/api/bestuurlijke-grenzen/v2/openbare-lichamen"
        apiKey: ${APIKEY}
    area:
      type: rest
      options:
        url: "https://brk.basisregistraties.overheid.nl/api/bestuurlijke-grenzen/v2/bestuurlijke-gebieden"
        apiKey: ${APIKEY}

