name: Release docs

on:
  push:
    tags:
      - '*'

jobs:
  release-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: gh release create $GITHUB_REF_NAME --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}